### PR TITLE
Add merge sort implementation

### PR DESCRIPTION
**Pull request by n3a9**

### CODE REVIEW

**Comment by n3a9** [comment]
Merge sort fails at specific conditions.

**Review by kirubarajan — CHANGES_REQUESTED** [review]
Still failing merge sorts tests? Is this an issue with the test or implementation?

**Comment by n3a9** [comment]
Implementation

**Comment by n3a9** [comment]
Should be fixed now @kirubarajan

**Review by kirubarajan — APPROVED** [review]

**Pull request merged**
