### PR TITLE
Factorial implementation

### PR DESCRIPTION
**Pull request by hamsterz0**

### CODE REVIEW

**Review by n3a9 — APPROVED** [review]

**Review by kirubarajan — DISMISSED** [review]
Can we remove the profanity in the error checking and rename the args variable to n (just for standard mathematic notation to make it easier for future development)?

**Comment by n3a9** [comment]
@kirubarajan First issue addressed in commit [1e584d7](https://github.com/eloreprojects/programjs/pull/27/commits/1e584d7250a33286103c303fe3fcb3c94bced49d).

**Comment by kirubarajan** [comment]
Isn't recursion beautiful? Try to keep the implementation as lightweight as possible by shedding code and using recursion as much as possible.

Tests should be also show the correct answers as well as the inputs and attempt to make it as clear to the developer what the issue with the code is.

Good implementation!

**Comment by n3a9** [comment]
Nice!

**Pull request merged**
